# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import app.grpc_server.protos.product_pb2 as product__pb2


class AServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TestVerificationCode = channel.unary_unary(
        '/proto.AService/TestVerificationCode',
        request_serializer=product__pb2.TestVerificationCodeRequest.SerializeToString,
        response_deserializer=product__pb2.TestVerificationCodeResponse.FromString,
        )
    self.IntegralChange = channel.unary_unary(
        '/proto.AService/IntegralChange',
        request_serializer=product__pb2.IntegralChangeRequest.SerializeToString,
        response_deserializer=product__pb2.IntegralChangeResponse.FromString,
        )


class AServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TestVerificationCode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IntegralChange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TestVerificationCode': grpc.unary_unary_rpc_method_handler(
          servicer.TestVerificationCode,
          request_deserializer=product__pb2.TestVerificationCodeRequest.FromString,
          response_serializer=product__pb2.TestVerificationCodeResponse.SerializeToString,
      ),
      'IntegralChange': grpc.unary_unary_rpc_method_handler(
          servicer.IntegralChange,
          request_deserializer=product__pb2.IntegralChangeRequest.FromString,
          response_serializer=product__pb2.IntegralChangeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.AService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
