# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='product.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rproduct.proto\x12\x05proto\",\n\x1bTestVerificationCodeRequest\x12\r\n\x05phone\x18\x01 \x01(\t\"N\n\x1cTestVerificationCodeResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"-\n\x15IntegralChangeRequest\x12\x14\n\x0corder_number\x18\x01 \x01(\t\":\n\x16IntegralChangeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xba\x01\n\x08\x41Service\x12_\n\x14TestVerificationCode\x12\".proto.TestVerificationCodeRequest\x1a#.proto.TestVerificationCodeResponse\x12M\n\x0eIntegralChange\x12\x1c.proto.IntegralChangeRequest\x1a\x1d.proto.IntegralChangeResponseb\x06proto3')
)




_TESTVERIFICATIONCODEREQUEST = _descriptor.Descriptor(
  name='TestVerificationCodeRequest',
  full_name='proto.TestVerificationCodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='proto.TestVerificationCodeRequest.phone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=68,
)


_TESTVERIFICATIONCODERESPONSE = _descriptor.Descriptor(
  name='TestVerificationCodeResponse',
  full_name='proto.TestVerificationCodeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='proto.TestVerificationCodeResponse.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone', full_name='proto.TestVerificationCodeResponse.phone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='proto.TestVerificationCodeResponse.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=148,
)


_INTEGRALCHANGEREQUEST = _descriptor.Descriptor(
  name='IntegralChangeRequest',
  full_name='proto.IntegralChangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_number', full_name='proto.IntegralChangeRequest.order_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=195,
)


_INTEGRALCHANGERESPONSE = _descriptor.Descriptor(
  name='IntegralChangeResponse',
  full_name='proto.IntegralChangeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='proto.IntegralChangeResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.IntegralChangeResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=255,
)

DESCRIPTOR.message_types_by_name['TestVerificationCodeRequest'] = _TESTVERIFICATIONCODEREQUEST
DESCRIPTOR.message_types_by_name['TestVerificationCodeResponse'] = _TESTVERIFICATIONCODERESPONSE
DESCRIPTOR.message_types_by_name['IntegralChangeRequest'] = _INTEGRALCHANGEREQUEST
DESCRIPTOR.message_types_by_name['IntegralChangeResponse'] = _INTEGRALCHANGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestVerificationCodeRequest = _reflection.GeneratedProtocolMessageType('TestVerificationCodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTVERIFICATIONCODEREQUEST,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:proto.TestVerificationCodeRequest)
  })
_sym_db.RegisterMessage(TestVerificationCodeRequest)

TestVerificationCodeResponse = _reflection.GeneratedProtocolMessageType('TestVerificationCodeResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTVERIFICATIONCODERESPONSE,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:proto.TestVerificationCodeResponse)
  })
_sym_db.RegisterMessage(TestVerificationCodeResponse)

IntegralChangeRequest = _reflection.GeneratedProtocolMessageType('IntegralChangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _INTEGRALCHANGEREQUEST,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:proto.IntegralChangeRequest)
  })
_sym_db.RegisterMessage(IntegralChangeRequest)

IntegralChangeResponse = _reflection.GeneratedProtocolMessageType('IntegralChangeResponse', (_message.Message,), {
  'DESCRIPTOR' : _INTEGRALCHANGERESPONSE,
  '__module__' : 'product_pb2'
  # @@protoc_insertion_point(class_scope:proto.IntegralChangeResponse)
  })
_sym_db.RegisterMessage(IntegralChangeResponse)



_ASERVICE = _descriptor.ServiceDescriptor(
  name='AService',
  full_name='proto.AService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=258,
  serialized_end=444,
  methods=[
  _descriptor.MethodDescriptor(
    name='TestVerificationCode',
    full_name='proto.AService.TestVerificationCode',
    index=0,
    containing_service=None,
    input_type=_TESTVERIFICATIONCODEREQUEST,
    output_type=_TESTVERIFICATIONCODERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IntegralChange',
    full_name='proto.AService.IntegralChange',
    index=1,
    containing_service=None,
    input_type=_INTEGRALCHANGEREQUEST,
    output_type=_INTEGRALCHANGERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASERVICE)

DESCRIPTOR.services_by_name['AService'] = _ASERVICE

# @@protoc_insertion_point(module_scope)
